import numpy as np
import matplotlib.pyplot as plt

# Load the files generated by your script
time_data = np.load("Troi_epochs_stride_0.126s_time.npy")
events = np.load("Troi_epochs_stride_0.126s_events.npy")

for label in [1, 2, 3, 4]:
    # Find all windows for this finger
    mask = events[:, 2] == label
    # Calculate the average "energy burst" (Variance) across channels
    energy = np.mean(np.var(time_data[mask], axis=2))
    print(f"Label {label} Average Energy: {energy:.2e}")

# The label with the highest Energy is your Thumb.
# The label with the lowest Energy is your Pinky.